apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marquez.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "marquez.name" . }}
    helm.sh/chart: {{ include "marquez.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "marquez.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "marquez.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.marquez.image.repository }}:{{ .Values.marquez.image.tag }}"
          imagePullPolicy: {{ .Values.marquez.image.pullPolicy }}
          volumeMounts:
            - name: marquez-volume
              mountPath: /usr/src/app/config.yml
              subPath: config.yml
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: MARQUEZ_CONFIG
              value: "/usr/src/app/config.yml"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: marquez-volume
        configMap:
          name: marquez-config
